### ISSUE TITLE
Bug: Fix the greet contributors workflow

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Contributors-Gallery#13]
**Description:**
We already have the `greet-contributor.yml` file in the `.github/workflow` folder, but it's not greeting the issue raisers and PR contributors.

**Tasks:**
- [ ]  Fix the issue to make the workflow work properly without changing the message.

**Comment by Junaid-Mohamed** [comment]
I would like to work on this can you please assign it to me

**Comment by Ferdinand-Ogama** [comment]
Hello, kindly assign me this issue.

**Comment by Pinaka-Pani-18** [comment]
> I would like to work on this can you please assign it to me

Assigned to you @Junaid-Mohamed, you can start fixing it.

**Comment by Pinaka-Pani-18** [comment]
> Hello, kindly assign me this issue.

Hi @Ferdinand-Ogama, As we are assigning issues on a first-come, first-served basis, please check other issues and leave a comment there. I will then assign you, or you can identify any issue and create one.

**Comment by Pinaka-Pani-18** [comment]
@Junaid-Mohamed any updates ?

**Comment by Junaid-Mohamed** [comment]
@Pinaka-Pani-18 I've made a PR for this issue couple of day's back please review it
reference #18
