### ISSUE TITLE
[ FEATURE ] - Create a contributors profile section

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Contributors-Gallery#14]
**Description:**
Create a contributors profile section below in a separate .jsx file, which you should create in `src/components`.

**Tasks:**
1. Create the contributors profile section in a separate .jsx file.
2. Create an "Add Profiles" button between the search and contributors profiles section.
3. Create dummy data for now with responsiveness.

**Comment by Petsamuel** [comment]
assign to me

**Comment by Pinaka-Pani-18** [comment]
> assign to me

assigned to you @Petsamuel , you can start working on it.
