### ISSUE TITLE
[ FEATURE ] - Create Workflow for First Contributors

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Contributors-Gallery#15]
**Description:**
If a contributor is the first to open an issue or create a pull request, create a workflow for them.

**Tasks:**
- [ ] Implement a workflow that identifies and responds to the first contributors who open issues or create pull requests.

**Comment by shrutimishra27** [comment]
I can work on it.
Plz assign it to me.

**Comment by Pinaka-Pani-18** [comment]
> I can work on it. Plz assign it to me.

Assigned to you @shrutimishra27, you can start working on it.

**Comment by shrutimishra27** [comment]
Thank you @Pinaka-Pani-18. Will submit the work soon.

Can you please check if this project is under <b>Hacktoberfest</b>? Because it is showing <b>Not-Participating</b>

**Comment by Pinaka-Pani-18** [comment]
> Thank you @Pinaka-Pani-18. Will submit the work soon.
> 
> Can you please check if this project is under Hacktoberfest? Because it is showing Not-Participating

I have checked it, and it still appears correct to me. Can you check once again and update me if it still appears as "not participating"?

**Comment by shrutimishra27** [comment]
> > Thank you @Pinaka-Pani-18. Will submit the work soon.
> > Can you please check if this project is under Hacktoberfest? Because it is showing Not-Participating
> 
> I have checked it, and it still appears correct to me. Can you check once again and update me if it still appears as "not participating"?

Yes now as I see, its showing that the <b>project is participating</b> in Hacktoberfest.
