### ISSUE TITLE
Create Issue Templates

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Contributors-Gallery#3]
**Description:**

In order to create issues effectively, we need to have issue templates for separate categories, including bug reports, feature requests, enhancements, documentation, miscellaneous, and questions.

**Tasks:**

- [ ] For every separate issue that includes 
- description, 
- screenshot (if applicable), 
- a task bar for contributors to indicate their willingness to work on the issue and 
- additional information field. 
- Also, include a link to star the repository.

**Additional Information:**
Issue templates will improve the project's organization and help contributors provide valuable information when reporting issues or seeking answers to their questions.

**Comment by Tashuuuu** [comment]
Can I work on this?

**Comment by Pinaka-Pani-18** [comment]
> Can I work on this?

yes, assigned to you @Tashuuuu. You can start working on it.

**Comment by Pinaka-Pani-18** [comment]
> > Can I work on this?
> 
> yes, assigned to you @Tashuuuu. You can start working on it.

any update @Tashuuuu ?

**Comment by Tashuuuu** [comment]
Will finish soon
