### ISSUE TITLE
Create Workflow to Greet Contributors

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Contributors-Gallery#4]
**Description:**

This workflow is designed to greet and express appreciation to contributors when they raise an issue or a pull request (PR) in the project.

### For Issue:

- [ ] Send a message to the contributor: 

- Hello user_name,
  Thank you for raising the issue. Soon, the maintainers/owner will review it and offer feedback and suggestions. If you enjoy contributing  to the project, please consider giving it a star ⭐.

shell

### For Pull Request (PR):

- [ ] Send a message to the contributor:

-   Good work user_name,
    Thank you for raising the PR. Soon, the maintainers/owner will review it and offer feedback and suggestions. If you enjoy contributing to the project, please consider giving it a star ⭐.

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this, please assign

**Comment by Pinaka-Pani-18** [comment]
> Hey, I would like to work on this, please assign

Assigned to you @IrfanSalim, start working on it
