### ISSUE TITLE
Create CONTRIBUTING.md File

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Contributors-Gallery#5]
**Description:**

In order to facilitate contributions from the open-source community, we need to create a `CONTRIBUTING.md` file that provides guidelines for contributing to this project.

**Tasks:**

- [ ] Create a `CONTRIBUTING.md` file that includes clear instructions on how to:
    1. **Installation:** Provide installation instructions for the project ( add a link to refer to the README.md file or include it here).
    2. **Contribution Guide:** Offer comprehensive guidelines for contributors, covering the entire process from forking the repository to pushing changes to our project. Include code snippets for clarity.
    3. **Visual Examples:** Add images for every code snippet with an example.
    4. **Issue:** Explain the process for creating issues.

**Additional Information:**

A well-defined `CONTRIBUTING.md` file is essential to attract and guide contributors effectively. It helps streamline the contribution process, maintain code quality, and promote a positive and inclusive community.

**Comment by tvermaashutosh** [comment]
@Pinaka-Pani-18 Please assign me this issue. I want to work on it and contribute to it.

**Comment by Pinaka-Pani-18** [comment]
> @Pinaka-Pani-18 Please assign me this issue. I want to work on it and contribute to it.

Hi @tvermaashutosh assigned, now you can start working on it.
