### ISSUE TITLE
Fix README.md by creating a logo

### ISSUE THREAD

**Issue by tvermaashutosh** [Pinaka-Pani-18/Contributors-Gallery#6]
Fix the `Contributors Gallery Logo` image not loading in the README.md file.

@Pinaka-Pani-18 Please assign me this issue. I'd like to work on and contribute to it.

**Comment by Pinaka-Pani-18** [comment]
> Fix the `Contributors Gallery Logo` image not loading in the README.md file.
> 
> @Pinaka-Pani-18 Please assign me this issue. I'd like to work on and contribute to it.

There is no logo in the README.md file. I will assign you if you would like to create one and place it in README.md

**Comment by rahulsingh5926** [comment]
please assign we a task ready to work in ur repo

**Comment by Pinaka-Pani-18** [comment]
> please assign we a task ready to work in ur repo

You will create a logo ? You will update it readme.md file right?

**Comment by rahulsingh5926** [comment]
yes i will create a logo and will update in readme.md

**Comment by Pinaka-Pani-18** [comment]
> yes i will create a logo and will update in readme.md

assigned to you @rahulsingh5926 , you can start working on it.

**Comment by 0silverback0** [comment]
if this task is not complete i can create a logo. Just give me details about what you would want it to look like
